name: Dispatch Event on Schema Update

on:
  push:
    branches:
      - master
    paths:
      - 'packages/api/src/schema/api-schema.yaml'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to JS SDK Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: suhailkakar/livepeer-js
          event-type: update-schema

